//! Input abstraction. The Zig code used `rl.KeyboardKey` directly throughout the
//! logic. Here we define our own `Key` so the MIDI mapping and UI state machine stay
//! free of the raylib dependency; `interface.rs` maps `raylib::consts::KeyboardKey`
//! into this enum at the edge.

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,
    Escape,
    Grave,
    Minus,
    Equal,
    Backspace,
    Tab,
    CapsLock,
    LeftShift,
    RightShift,
    LeftControl,
    RightControl,
    LeftAlt,
    RightAlt,
    LeftSuper,
    RightSuper,
    LeftBracket,
    RightBracket,
    Backslash,
    Semicolon,
    Apostrophe,
    Enter,
    Comma,
    Period,
    Slash,
    Space,
    Up,
    Down,
    Left,
    Right,
    Delete,
}

/// The keys polled each frame (mirrors `interface.poll_keys`).
pub const POLL_KEYS: [Key; 66] = {
    use Key::*;
    [
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Zero,
        One,
        Two,
        Three,
        Four,
        Five,
        Six,
        Seven,
        Eight,
        Nine,
        Escape,
        Grave,
        Minus,
        Equal,
        Backspace,
        Tab,
        CapsLock,
        LeftShift,
        RightShift,
        LeftControl,
        RightControl,
        LeftAlt,
        RightAlt,
        LeftSuper,
        RightSuper,
        LeftBracket,
        RightBracket,
        Backslash,
        Semicolon,
        Apostrophe,
        Enter,
        Comma,
        Period,
        Slash,
        Space,
        Up,
        Down,
        Left,
        Right,
        Delete,
    ]
};

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum EventType {
    KeyPress,
    KeyRelease,
}

#[derive(Clone, Copy, Debug)]
pub struct Event {
    pub ty: EventType,
    pub key: Key,
}
