[package]
name = "firmware"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.6", features = ["arch-cortex-m", "executor-thread", "integrated-timers"] }
embassy-rp = { version = "0.2", features = ["time-driver", "critical-section-impl"] }
embassy-time = { version = "0.3", features = ["tick-hz-1_000_000"] }
cortex-m-rt = "0.7"
panic-halt = "0.2"
