name: kicad diff

permissions:
  pull-requests: write  # Allows posting comments on PRs
  contents: write  # Allows pushing changes
  pages: write  # Needed for GitHub Pages deployment
  id-token: write  # Required for authentication

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
    - opened
    - synchronize
    paths:
    - 'schematics/**'

env:
    PROJECT_FILE: "hardware/board/board.kicad_pro"

jobs:
  kiri-diff:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Kiri
      uses: hacker-fab/kiri-github-action@v2.0.5
      with:
        project-file: ${{ env.PROJECT_FILE }}
