name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fuzz:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Install Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.15.1
    - name: Fuzz
      run: zig build fuzz --summary all
